### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by lukefretwell** [cagov/codecagov#10]
- [ ] review/edit MVP: https://docs.google.com/document/d/1hXYzV_KW49epVuj9EuUGP1hNNARRMf_yVi1Uz5XX_oI/edit#heading=h.prd1f640t6hb ( @marctjones @abquirarte )
- [ ] add to Code California website
- [ ] link where appropriate (website/strategy doc/sign-up messaging)
- [ ] post 'final' version to community

**Comment by davisopendataguy** [comment]
Well done. And a marker for the rest of government.

Sent from my iPhone

On Oct 15, 2018, at 12:27 PM, Luke Fretwell <notifications@github.com<mailto:notifications@github.com>> wrote:


Added an MVP one here since we're standing up the community:

https://github.com/cagov/codeCAgov/wiki/Code-of-conduct<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcagov%2FcodeCAgov%2Fwiki%2FCode-of-conduct&data=02%7C01%7Cstuart.drown%40govops.ca.gov%7C79d6d43b14024697e68c08d632d43050%7C68a88534151d4e79804609be7890656c%7C0%7C0%7C636752284267707273&sdata=O3f6LiVPpaB90yE1J3kn6VXeJeop%2FJUkYOoonuVrUp0%3D&reserved=0>

Adding checklist items to original comment.

**Comment by lukefretwell** [comment]
Addressed in 'What we strive for':

https://codecagov-playbook.readthedocs.io/en/latest/about/#what-we-strive-for
